services:
  mysql:
    image: 'mysql:8.0.30'
    environment:
      - 'MYSQL_DATABASE=db'
      - 'MYSQL_ROOT_PASSWORD=root'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - '3306'
